In [1]:
%pip install datasets pandas transformers python-dotenv peft

  Using cached dill-0.3.8-py3-none-any.whl.metadata (10 kB)
  Using cached multiprocess-0.70.16-py312-none-any.whl.metadata (7.2 kB)
Using cached dill-0.3.8-py3-none-any.whl (116 kB)
Using cached multiprocess-0.70.16-py312-none-any.whl (146 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.8/30.8 MB 25.9 MB/s eta 0:00:00a 0:00:01
  Attempting uninstall: fsspec0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/8 [pyarrow]
    Found existing installation: fsspec 2025.5.1━━━━━━━━━━━━━━ 1/8 [pyarrow]
    Uninstalling fsspec-2025.5.1:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/8 [pyarrow]
      Successfully uninstalled fsspec-2025.5.1━━━━━━━━━━━━━━━━ 1/8 [pyarrow]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [peft]7/8 [peft]ets]e]s]


In [2]:
import os
from dotenv import load_dotenv
load_dotenv()

True

In [6]:
hf_token = os.getenv("HF_TOKEN")
# print(hf_token)

In [7]:
from huggingface_hub import login

/Users/thangaraj/Documents/Krish Naik/Agentic AI/venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [8]:
login(token=hf_token)

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.


In [9]:
from transformers import AutoModelForCausalLM, AutoTokenizer
model_name = "distilgpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token # end of string token
tokenizer.padding_size = "right"


In [10]:
model = AutoModelForCausalLM.from_pretrained(model_name)
print(model)

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-5): 6 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)


In [11]:
text = "ஒரு நாள் "
inputs = tokenizer(text, return_tensors="pt")
print(inputs['input_ids'])

tensor([[156, 106, 240, 156, 106, 108, 156, 107, 223, 220, 156, 106, 101, 156,
         106, 122, 156, 106, 111, 156, 107, 235, 220]])


In [16]:
output2 = model.generate(inputs.input_ids, max_new_tokens = 100)
print(output2)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


tensor([[156, 106, 240, 156, 106, 108, 156, 107, 223, 220, 156, 106, 101, 156,
         106, 122, 156, 106, 111, 156, 107, 235, 220, 156, 106, 101, 156, 106,
         122, 156, 106, 111, 156, 107, 235, 220, 156, 106, 101, 156, 106, 122,
         156, 106, 111, 156, 107, 235, 220, 156, 106, 101, 156, 106, 122, 156,
         106, 111, 156, 107, 235, 220, 156, 106, 101, 156, 106, 122, 156, 106,
         111, 156, 107, 235, 220, 156, 106, 101, 156, 106, 122, 156, 106, 111,
         156, 107, 235, 220, 156, 106, 101, 156, 106, 122, 156, 106, 111, 156,
         107, 235, 220, 156, 106, 101, 156, 106, 122, 156, 106, 111, 156, 107,
         235, 220, 156, 106, 101, 156, 106, 122, 156, 106, 111]])


In [13]:
output = model.generate(inputs['input_ids'], max_new_tokens = 100)
print(output)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


tensor([[156, 106, 240, 156, 106, 108, 156, 107, 223, 220, 156, 106, 101, 156,
         106, 122, 156, 106, 111, 156, 107, 235, 220, 156, 106, 101, 156, 106,
         122, 156, 106, 111, 156, 107, 235, 220, 156, 106, 101, 156, 106, 122,
         156, 106, 111, 156, 107, 235, 220, 156, 106, 101, 156, 106, 122, 156,
         106, 111, 156, 107, 235, 220, 156, 106, 101, 156, 106, 122, 156, 106,
         111, 156, 107, 235, 220, 156, 106, 101, 156, 106, 122, 156, 106, 111,
         156, 107, 235, 220, 156, 106, 101, 156, 106, 122, 156, 106, 111, 156,
         107, 235, 220, 156, 106, 101, 156, 106, 122, 156, 106, 111, 156, 107,
         235, 220, 156, 106, 101, 156, 106, 122, 156, 106, 111]])


In [14]:
print(tokenizer.decode(output[0], skip_special_tokens=True))

ஒரு நாள் நாள் நாள் நாள் நாள் நாள் நாள் நாள் நாள


In [17]:
print(tokenizer.decode(output2[0], skip_special_tokens=True))

ஒரு நாள் நாள் நாள் நாள் நாள் நாள் நாள் நாள் நாள


In [18]:
from datasets import load_dataset

In [19]:
raw_data = load_dataset("tniranjan/aitamilnadu_tamil_stories_no_instruct", split="train[:1000]")
print(raw_data)

Generating validation split: 100%|██████████| 121/121 [00:00<00:00, 11607.94 examples/s]

Dataset({
    features: ['text'],
    num_rows: 1000
})


In [20]:
data = raw_data.train_test_split(train_size=0.95) # 95 % for training
print(data)

DatasetDict({
    train: Dataset({
        features: ['text'],
        num_rows: 950
    })
    test: Dataset({
        features: ['text'],
        num_rows: 50
    })
})


In [21]:
tokenizer.pad_token = tokenizer.eos_token

In [24]:
def preprocess_batch(batch):
    return tokenizer(batch["text"], truncation=True, padding=True, max_length=200)

In [25]:
tokenized_dataset = data.map(
    preprocess_batch,
    batched=True,
    batch_size=4, # is batch is chunking ?
    remove_columns=data["train"].column_names,)

Map: 100%|██████████| 50/50 [00:00<00:00, 239.26 examples/s]


In [26]:
print(tokenized_dataset)

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask'],
        num_rows: 950
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask'],
        num_rows: 50
    })
})


In [30]:
print(tokenized_dataset['test']['attention_mask'])

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [31]:
# data collator for padding in equal size and much efficient pre processing like eos token etc.

from transformers import DataCollatorForLanguageModeling

In [32]:
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)
print(data_collator)

DataCollatorForLanguageModeling(tokenizer=GPT2TokenizerFast(name_or_path='distilgpt2', vocab_size=50257, model_max_length=1024, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>', 'pad_token': '<|endoftext|>'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
}
), mlm=False, mlm_probability=0.15, mask_replace_prob=0.8, random_replace_prob=0.1, pad_to_multiple_of=None, tf_experimental_compile=False, return_tensors='pt', seed=None)


scaling = 8
aplpha = 32


which means  -> alpha / scaling.

32 / 8 = 4

out put gets maximized or sclaed or zoomed to 4 times.

dropout for stability -> which reduces over fitting. which makes the weights 0 and vary the weights. fine tune happens only when the wights adjusts itself. 

bias = "none" which tells to fine-tune the parameters only in lora. don't touch the base model.




In [33]:
from peft import get_peft_model, LoraConfig, TaskType

In [35]:
lora_config = LoraConfig(
    r = 8, # rank of lora matrices -> adjust it for speed or memory tradeoff
    lora_alpha=32, # this is scaling factor
    bias = "none", # no extra bias parameters
    lora_dropout=0.1, # drop out for stability.
    task_type=TaskType.CAUSAL_LM #since we are fine tuning GPT style models.
)



Apply the mentioned LoRa to the model



In [36]:
model = get_peft_model(model, lora_config)

/Users/thangaraj/Documents/Krish Naik/Agentic AI/venv/lib/python3.13/site-packages/peft/tuners/lora/layer.py:1768: UserWarning: fan_in_fan_out is set to False but the target module is `Conv1D`. Setting fan_in_fan_out to True.
  warnings.warn(


In [37]:
model.print_trainable_parameters()

trainable params: 147,456 || all params: 82,060,032 || trainable%: 0.1797






Lets start taining




In [38]:
model.train() #This ensures layers like Dropout & BatchNorm are active during training.
from torch.optim import AdamW  # Correct import
# Define new optimizer
optimizer = AdamW(model.parameters(), lr=1e-5)
from transformers import TrainingArguments, Trainer
training_args = TrainingArguments(
output_dir="./output",
# evaluation_strategy="epoch",
#save_strategy="epoch",
save_steps=500,
learning_rate=1e-5,
weight_decay=0.01,
num_train_epochs=3, # gives the data 3 times / trains 3 times
per_device_train_batch_size=2,    # Batch size (adjust for GPU memory)
per_device_eval_batch_size=2,
logging_steps=50,
logging_dir="./logs",
resume_from_checkpoint=True # incase of disruption, resume from the check point.
)
trainer = Trainer(
    model = model,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    args=training_args,
    optimizers=(optimizer, None),
    data_collator=data_collator
)
trainer.train()


TypeError: TrainingArguments.__init__() got an unexpected keyword argument 'evaluation_strategy'